# Generated by Django 6.0.2 on 2026-04-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0002_schedule_max_value_schedule_min_rooms"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomUnavailableWindow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day_of_week", models.CharField(choices=[("MON", "Monday"), ("TUE", "Tuesday"), ("WED", "Wednesday"), ("THU", "Thursday"), ("FRI", "Friday"), ("SAT", "Saturday")], max_length=10)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("room", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="unavailable_windows", to="scheduler.room")),
            ],
        ),
    ]
