# Generated by Django 6.0.2 on 2026-04-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0003_roomunavailablewindow"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsession",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="classsession",
            name="teacher_unavailable_days",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
