# Generated by Django 6.0.2 on 2026-04-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0004_classsession_is_locked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="features",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="classsession",
            name="required_features",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
