# Generated by Django 6.0.2 on 2026-04-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0005_room_features_classsession_required_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
