# Generated by Django 6.0.2 on 2026-04-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0006_schedule_status_published_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("program", models.CharField(blank=True, default="", max_length=100)),
                ("semester", models.PositiveIntegerField(default=1)),
                ("size", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("department", models.CharField(blank=True, default="", max_length=100)),
                ("max_daily_load", models.PositiveIntegerField(default=4)),
                ("unavailable_days", models.CharField(blank=True, default="", max_length=100)),
            ],
        ),
    ]
