# Generated by Django 6.0.2 on 2026-04-21 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0007_teacher_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsession",
            name="section_record",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="class_sessions", to="scheduler.section"),
        ),
        migrations.AddField(
            model_name="classsession",
            name="teacher_record",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="class_sessions", to="scheduler.teacher"),
        ),
    ]
