# Generated by Django 6.0.2 on 2026-04-21 01:20

from django.db import migrations


def backfill_classsession_links(apps, schema_editor):
    ClassSession = apps.get_model("scheduler", "ClassSession")
    Teacher = apps.get_model("scheduler", "Teacher")
    Section = apps.get_model("scheduler", "Section")

    teachers_by_name = {teacher.name: teacher for teacher in Teacher.objects.all()}
    sections_by_name = {section.name: section for section in Section.objects.all()}

    for session in ClassSession.objects.all():
        update_fields = []

        teacher = teachers_by_name.get(session.teacher)
        if teacher and session.teacher_record_id is None:
            session.teacher_record_id = teacher.id
            session.teacher_unavailable_days = teacher.unavailable_days
            update_fields.extend(["teacher_record", "teacher_unavailable_days"])

        section = sections_by_name.get(session.batch)
        if section and session.section_record_id is None:
            session.section_record_id = section.id
            update_fields.append("section_record")

        if update_fields:
            session.save(update_fields=update_fields)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0008_classsession_teacher_record_section_record"),
    ]

    operations = [
        migrations.RunPython(backfill_classsession_links, noop_reverse),
    ]
