# Generated by Django 6.0.2 on 2026-04-21 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='fixed_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_class_sessions', to='scheduler.room'),
        ),
    ]
